# Vagrantfile
# :: mt08
# http://qiita.com/mt08/items/ccc660f233e0f525b0da

VB_NAME="Moebuntu 16.10"
VM_MEMORY=2048
VM_CORES=2
VM_HOSTNAME="moebuntu.localdomain"
VM_BASE_BOX="box-cutter/ubuntu1610-desktop"

Vagrant.configure("2") do |config|
	config.vm.box = VM_BASE_BOX
	#config.vm.network "forwarded_port", guest: 80, host: 8080
	#config.vm.network "public_network", bridge: 'Intel(R) Ethernet Connection I217-LM'
	config.vm.hostname = VM_HOSTNAME

	config.vm.provider "virtualbox" do |vb|
		#   vb.gui = true
		vb.name = VB_NAME
		vb.memory = VM_MEMORY
		vb.cpus = VM_CORES
	end

	config.vm.provision "shell", inline: <<-SHELL
		#
		if [ ! -f $HOME/.vagrant-provision1-done ]; then
			echo 'Acquire::http::Proxy "http://linux64:3142";' | tee /etc/apt/apt.conf.d/02proxy
			#
			# Locale setting: Japanese
			locale-gen "ja_JP.UTF-8"
			localectl set-locale LANG=ja_JP.UTF-8
			#
			wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- |  apt-key add -
			wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- |  apt-key add -
			wget https://www.ubuntulinux.jp/sources.list.d/yakkety.list -O /etc/apt/sources.list.d/ubuntu-ja.list
			apt-get update
			apt-get install -y ubuntu-defaults-ja
			#
			apt-get install -y compizconfig-settings-manager unity-tweak-tool
			apt-get install -y imagemagick dos2unix

			apt-get -q update -q
			DEBIAN_FRONTEND=noninteractive apt-get -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
			#
			touch $HOME/.vagrant-provision1-done
		else
			echo "Skipping the initail setup ..."
		fi
	SHELL

	config.vm.provision "shell", privileged: false, inline: <<-SHELL
		export MOE_BASE_COLOR=Pink
		export MOE_THEME_REVISION=10
		for i in "MoeSetupTheme.sh" "MoeSetupFont.sh" "MoeSetupWallpaper.sh"; do
		    file /vagrant/$i | grep CRLF &&	dos2unix /vagrant/$i
			bash /vagrant/$i
		done
	SHELL
end
